In [ ]:
array- homogeneous(shape,datatype)
list- hetrogeneous

np.array(['str',1,2,3.0])

In [ ]:
https://drive.google.com/file/d/1kH0ahkbArd6rKVFjezlV4Ws_kFubzVqK/view?usp=sharing

In [ ]:
1. Create a numpy array with numpy.array module and with a data type integer and float.


In [ ]:
import numpy as np
x=np.array([2,4,2,1,3],dtype='int')
y=np.array([2,4,2,1,3],dtype='float')
print(x)
print(y)
y.shape

[2 4 2 1 3]
[2. 4. 2. 1. 3.]


(5,)

In [ ]:
2. Create numpy arrays that have zero, one, two, three dimensions respectively.
#Also, print the shape and dimensions of the numpy arrays created above.

In [ ]:
#zero dimension
a_0=np.array(5)
#shape()
# 0-()
# 1-(a,)- no of elements in the array
# 2-(a,b)
# 3-(a,b,c)

print(a_0)
print(a_0.shape)
print(a_0.ndim)

5
()
0


In [ ]:
#1 dimension
a_1=np.array([2,4,2,1,3],dtype='float')

print(a_1)
print(a_1.shape)
print(a_1.ndim)

[2. 4. 2. 1. 3.]
(5,)
1


In [ ]:
#2 dimension
a_2=np.array([[1,2,3,4,5],[10,9,10,8,7]])
print(a_2)
print(a_2.shape)
# 2-(a,b)
#a-no of 1d array
#b-no of values in each 1d array
print(a_2.ndim)

[[ 1  2  3  4  5]
 [10  9 10  8  7]]
(2, 5)
2


In [ ]:
#3 dimension
a_3=np.random.randint(10,20,(3,3,5))
print(a_3)
print(a_3.shape)
# 3-(a,b,c)
#a- no of 2d array
#b-no of 1d array in each 2d array
#c-no of values in each 1d array
print(a_3.ndim)

[[[17 12 17 18 19]
  [13 12 11 13 14]
  [19 10 13 10 18]]

 [[17 18 10 12 12]
  [18 12 13 17 18]
  [12 13 11 19 10]]

 [[10 10 17 18 18]
  [18 15 15 17 15]
  [15 12 18 16 17]]]
(3, 3, 5)
3


In [ ]:
3. Create a 2x3, 3x3, and 4x4 identity matrix using numpy.


In [ ]:
#identity(3)-square
#eye(a,b)

In [ ]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(2,3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [ ]:
4. Create a numpy array with shape 2x5 that has all the elements as zero.

In [ ]:
np.zeros((2,5),dtype='int')

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
5. Create a numpy array that has the shape 3x5 and all the elements are 5

In [ ]:
np.full((3,5),5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [ ]:
6. Create a numpy array with random integers in the range 0-100, and the sample size
should be 25.


In [ ]:
np.random.randint(0,100,25)

array([63, 44, 59, 63,  2,  9, 75, 45, 45, 90, 35, 63, 93, 63, 16, 12, 18,
       18, 15,  9, 57, 40, 84,  1, 38])

In [ ]:
7. Create a numpy array with a shape 3x3 that has all elements as 1.


In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
8. Create a numpy array in the shape 2x3 with random integers in the range 0-100.
Reshape the array in the shape 3x2 and print the updated shape of the resultant array.


In [ ]:
x=np.random.randint(0,100,(2,3))
x

array([[12, 98, 66],
       [80, 89, 76]])

In [ ]:
#.reshape()
#1x6, 6x1, 2x3, 3x2-2d
#(1,1,6),(1,2,3),(2,1,3)

In [ ]:
x.reshape(3,2)

array([[12, 98],
       [66, 80],
       [89, 76]])

In [ ]:
x.T

array([[12, 80],
       [98, 89],
       [66, 76]])

In [ ]:
9. Create a random array, with the range 0-1000, with a size 50. Perform the
following operations on the same.
a. Print the first ten elements of the array.
b. Print the last ten elements of the array
c. Print the elements from the indexes 10-25
d. Print the element at the index 22
e. Print the array using negative indexing.
f. Print the last ten elements of the array, using negative indexing.


In [ ]:
x=np.random.randint(0,1000,50)

In [ ]:
# a. Print the first ten elements of the array.
x[:10]

array([ 50, 242, 266, 305, 246, 662, 859, 220, 987, 763])

In [ ]:
# b. Print the last ten elements of the array
x[-10:]

array([ 37, 308,  38, 974, 985, 685, 947,  69, 957, 142])

In [ ]:
# c. Print the elements from the indexes 10-25
x[10:26]

array([326,  75, 447, 963, 452, 713, 258, 562,   5, 304, 254, 215, 646,
       424, 556, 865])

In [ ]:
# d. Print the element at the index 22
x[22]

646

In [ ]:
# Print the array using negative indexing.
x[-30:-15]

array([254, 215, 646, 424, 556, 865, 779, 388, 930, 705, 952, 287, 602,
       867, 695])

In [ ]:
10. Given a numpy array that has values = [1,2,3,4,5]. Perform the following operations.
a. Insert the element 6 at the end of the array.
b. Insert the element 10 at the beginning of the array.
c. Insert the element 30, before 4.
d. Update the element 5 as 50.
e. Delete the element 50 in the updated array.
f. Create a function to search for the element 30.
g. Sort the array in ascending order.

In [ ]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [ ]:
# a. Insert the element 6 at the end of the array.
arr=np.append(arr,6)

In [ ]:
arr

array([1, 2, 3, 4, 5, 6])

In [ ]:
# b. Insert the element 10 at the beginning of the array.
arr=np.insert(arr,0,10)

In [ ]:
arr

array([10,  1,  2,  3,  4,  5,  6])

In [ ]:
# c. Insert the element 30, before 4.
np.where(arr==4)[0][0]

5

In [ ]:
arr=np.insert(arr,np.where(arr==4)[0][0],30)
arr

array([10,  1,  2,  3, 30,  4,  5,  6])

In [ ]:
# d. Update the element 5 as 50.
np.where(arr==5)[0][0]

6

In [ ]:
arr[6]=50

In [ ]:
arr

array([10,  1,  2,  3, 30,  4, 50,  6])

In [ ]:
# e. Delete the element 50 in the updated array.
np.delete(arr,np.where(arr==50)[0][0])

array([10,  1,  2,  3, 30,  4,  6])

In [ ]:
f. Create a function to search for the element 30.
g. Sort the array in ascending order.

In [ ]:
def search(arr,value):
  for i in arr:
    if i==value:
      print(f"{value}: is found")
      break
  else:
     print(f"{value} is not found")
search(arr,30)

30: is found


In [ ]:
#sorting
np.sort(arr)

array([ 1,  2,  3,  4,  6, 10, 30, 50])

In [ ]:
x=np.random.randint(1,20,(3,5))
#(a,b)
x

array([[ 1,  2,  2,  9,  5],
       [ 6, 19, 14,  8,  3],
       [ 8, 13, 15,  3,  7]])

In [ ]:
x[:1,2:4]

array([[2, 9]])

In [ ]:
x=[[1,2,3],[2,3,1]]
x[0][1:]

[2, 3]

In [ ]:
0,1,2

[0:2]

In [2]:
!git clone https://github.com/Saitejamacha/Data_Science_-_AI_ML.git

Cloning into 'Data_Science_-_AI_ML'...
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 6 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (6/6), 112.27 KiB | 1.58 MiB/s, done.


In [4]:
import shutil

# Make sure this matches your actual notebook filename
shutil.copy("/content/Numpy_Handson_22_2.ipynb", "/content/Data_Science_-_AI_ML/")


FileNotFoundError: [Errno 2] No such file or directory: '/Numpy_Handson_22_2.ipynb'

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive
